#!/bin/bash

echo 'After hook'
echo 'Installing CTags'
brew install ctags

echo 'Install atom packages'
apm install atom-material-ui
apm install atom-ctags
apm install rails-rspec
apm install rails-open-spec
apm install vim-mode
