#!/bin/bash

echo 'After hook'
echo 'Installing CTags'
brew install ctags

echo 'Install atom packages'
apm install atom-material-ui
apm install atom-ctags
apm install rails-rspec
apm install rails-open-spec
apm install vim-mode
apm install zen
apm install editor-stats
apm install expand-region

echo 'Moving atom config'
cp -r .dotfiles/.atom ./

echo 'Speeding up default cursor speed'
defaults write NSGlobalDomain KeyRepeat -int 0

echo 'Speeding up full screen animation'
defaults write -g NSWindowResizeTime -float 0.003

echo 'Make mission control animation instand'
defaults write com.apple.dock expose-animation-duration -float 0
